# Generated by Django 6.0.2 on 2026-03-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
