"""
Django settings for vehicleVault project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=p5u!ikda5jpe6-isgf#75lly5^*r8ux+(x&$ukjivrhd5z+ze'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',                          # ← must be BEFORE django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'compare',
]

# ── Jazzmin Admin Theme ───────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # Title in browser tab and top-left of admin
    "site_title":        "VehicleVault Admin",
    "site_header":       "VehicleVault",
    "site_brand":        "VehicleVault",
    "welcome_sign":      "Welcome to VehicleVault Admin Panel",
    "copyright":         "VehicleVault © 2026",

    # Top menu links
    "topmenu_links": [
        {"name": "Home",          "url": "admin:index"},
        {"name": "View Site",     "url": "/",         "new_window": True},
        {"name": "Car List",      "url": "/compare/cars/",      "new_window": True},
        {"name": "User Dashboard","url": "/compare/user/",       "new_window": True},
    ],

    # User menu (top right)
    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
    ],

    # Sidebar icons for each model
    "icons": {
        "auth":                    "fas fa-users-cog",
        "auth.Group":              "fas fa-users",
        "core.User":               "fas fa-user",
        "compare.Car":             "fas fa-car",
        "compare.CarVariant":      "fas fa-layer-group",
        "compare.Accessory":       "fas fa-wrench",
        "compare.CarAccessoryMapping": "fas fa-link",
        "compare.Review":          "fas fa-star",
        "compare.Comparison":      "fas fa-balance-scale",
        "compare.SearchHistory":   "fas fa-search",
        "compare.UserInteraction": "fas fa-mouse-pointer",
        "compare.UserPreference":  "fas fa-sliders-h",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # Side menu order
    "order_with_respect_to": [
        "core",
        "core.User",
        "compare",
        "compare.Car",
        "compare.CarVariant",
        "compare.Accessory",
        "compare.Review",
        "compare.Comparison",
        "compare.SearchHistory",
        "compare.UserInteraction",
        "compare.UserPreference",
        "compare.CarAccessoryMapping",
    ],

    # Hide these from sidebar
    "hide_apps": [],
    "hide_models": [],

    # UI tweaks
    "show_sidebar":           True,
    "navigation_expanded":    True,
    "related_modal_active":   True,
    "custom_css":             None,
    "custom_js":              None,
    "use_google_fonts_cdn":   True,
    "show_ui_builder":        False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text":    False,
    "footer_small_text":    False,
    "body_small_text":      False,
    "brand_small_text":     False,
    "brand_colour":         "navbar-danger",    # red brand bar
    "accent":               "accent-danger",    # red accent
    "navbar":               "navbar-dark",
    "no_navbar_border":     True,
    "navbar_fixed":         True,
    "layout_boxed":         False,
    "footer_fixed":         False,
    "sidebar_fixed":        True,
    "sidebar":              "sidebar-dark-danger",  # dark sidebar with red highlights
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme":                "darkly",           # dark theme like your design
    "dark_mode_theme":      "darkly",
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vehicleVault.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vehicleVault.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'VehicleVault',
        'USER': 'postgres',
        'PASSWORD': 'Hiren123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
AUTH_USER_MODEL = 'core.User'

# Use email as login credential for both custom views and Django admin
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailBackend',
]
LOGIN_URL = '/core/login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hk.nakum2225@gmail.com'
EMAIL_HOST_PASSWORD = 'tayz dzcn whlo mrpx'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'