# Generated by Django 6.0.2 on 2026-03-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='car3',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='car4',
        ),
    ]
