# Generated by Django 6.0.2 on 2026-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_remove_comparison_car3_remove_comparison_car4'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carImage',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
