# Generated by Django 6.0.2 on 2026-03-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_car_sketchfabid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='sketchfabId',
        ),
        migrations.AddField(
            model_name='car',
            name='car3DModel',
            field=models.FileField(blank=True, null=True, upload_to='car_models/'),
        ),
    ]
