# Generated by Django 6.0.2 on 2026-03-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0007_remove_car_sketchfabid_car_car3dmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sketchfabId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
