# Generated by Django 6.0.2 on 2026-03-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0008_car_sketchfabid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car3DModel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sketchfabId',
        ),
        migrations.AddField(
            model_name='car',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='car_models/'),
        ),
        migrations.CreateModel(
            name='CarVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variantName', models.CharField(max_length=100)),
                ('variantTier', models.CharField(choices=[('Base', 'Base'), ('Mid', 'Mid'), ('Top', 'Top'), ('Special', 'Special Edition')], default='Base', max_length=20)),
                ('price', models.IntegerField()),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=30)),
                ('features', models.TextField(blank=True, help_text='Comma-separated list of features, e.g. Sunroof, Cruise Control')),
                ('isAvailable', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='compare.car')),
            ],
            options={
                'db_table': 'car_variant',
                'ordering': ['price'],
            },
        ),
    ]
