# Generated by Django 6.0.2 on 2026-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_remove_car_car3dmodel_remove_car_sketchfabid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car3DModel',
            field=models.FileField(blank=True, null=True, upload_to='car_models/'),
        ),
        migrations.AddField(
            model_name='car',
            name='sketchfabId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
