# Generated by Django 6.0.2 on 2026-03-30 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_car_car3dmodel_car_sketchfabid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('votes_car1', models.PositiveIntegerField(default=0)),
                ('votes_car2', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('car1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_car1', to='compare.car')),
                ('car2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_car2', to='compare.car')),
            ],
            options={
                'db_table': 'car_battle',
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_for', models.IntegerField(choices=[(1, 'Car 1'), (2, 'Car 2')])),
                ('votedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='compare.carbattle')),
            ],
            options={
                'db_table': 'battle_vote',
                'unique_together': {('battle', 'user')},
            },
        ),
    ]
