# Generated by Django 6.0.2 on 2026-03-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_carbattle_battlevote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('note', models.CharField(blank=True, help_text="e.g. 'Price hike', 'Festive discount', 'New variant launch'", max_length=200)),
                ('recorded_on', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='compare.car')),
            ],
            options={
                'db_table': 'car_price_history',
                'ordering': ['recorded_on'],
            },
        ),
    ]
