# Generated by Django 6.0.2 on 2026-04-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0012_carpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text='Full name of the owner', max_length=150)),
                ('owner_contact', models.CharField(blank=True, help_text='Phone / email (admin-only, not shown to users)', max_length=100)),
                ('purchase_date', models.DateField(help_text='Date this owner purchased / received the car')),
                ('sale_date', models.DateField(blank=True, help_text='Date this owner sold the car (leave blank if still current owner)', null=True)),
                ('purchase_price', models.IntegerField(blank=True, help_text='Price at which this owner bought the car (₹)', null=True)),
                ('notes', models.TextField(blank=True, help_text='e.g. accident history, condition at handover')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='compare.car')),
            ],
            options={
                'db_table': 'car_ownership',
                'ordering': ['purchase_date'],
            },
        ),
    ]
